### ISSUE TITLE
Pendaftaran Guru oleh Admin.

### ISSUE THREAD

**Issue by YanuarWanda** [YanuarWanda/ujianSekolah#2]
# Masalah 1 

### Thesis 1 :
Apakah guru harus ada sistem registrasinya?
### Argumentasi 1 :
Karena kalau guru hanya bisa ditambah oleh admin jadinya karagok.

# Masalah 2

### Thesis 2 :
Kalau misalnya pendaftaran guru hanya bisa dilakukan oleh admin, apakah perlu menambahkan foto? 
### Argumentasi 2 :
Karena IMO lebih baik nanti aja diganti oleh dianya sendiri (bukan oleh admin).

Mohon bantuannya.:smile:

**Comment by fahrimz** [comment]
Liat remote tv saya ga?

**Comment by wsetiawan** [comment]
Ada, dijual

**Comment by YanuarWanda** [comment]
Kan remotenya pake hp xiaomei

**Comment by YanuarWanda** [comment]
Kan remotenya pake hp xiaomei

**Comment by YanuarWanda** [comment]
Jadi yang ini jawabannya mana bang?

**Comment by fahrimz** [comment]
Guru bisa Registrasi sendiri, juga bisa import datanya Dari Excel, di importnya oleh admin.
