### ISSUE TITLE
Upload File

### ISSUE THREAD

**Issue by YanuarWanda** [YanuarWanda/ujianSekolah#4]
# Masalah 1
-------
### Thesis 1
Bagaimana cara mengganti file gambar di penyimpanan dengan gambar baru?

### Argumentasi 1
Belum terpecahkan.

Mohon bantuannya.:smile:

**Comment by fahrimz** [comment]
Yang replace belum bisa ya?

**Comment by YanuarWanda** [comment]
Udah bisa pake cara hapus dulu gambar sebelumnya terus tambah gambar yang baru.
