### ISSUE TITLE
CSS Preloader initial HTML flash

### ISSUE THREAD

**Issue by fahrimz** [YanuarWanda/ujianSekolah#5]
#ask
Nyoba pake preloader untuk nutupin content (loading), tapi si content muncul dulu sebelum ketutup preloader, ada solusi ? @YanuarWanda #

**Comment by YanuarWanda** [comment]
ini teh preloader yang ku urang dicomment tea? @FahriMZ

**Comment by fahrimz** [comment]
Beda mas
